version: '3.8'

services:
  pdf-parser:
    build: .
    container_name: pdf-parser-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONUNBUFFERED=1
    volumes:
      - ./model_cache:/root/.cache
      - ./model_cache/torch:/root/.cache/torch
      - ./model_cache/easyocr:/root/.EasyOCR
    restart: unless-stopped
    mem_limit: 8g
    mem_reservation: 4g
    cpus: '2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 300s